---

GENERAL:
  interaction_mode: speech
  agents: 1
  use_gui: True
  generic: True
  gui_title: Dialogues with Plato
  gui_title_agent_0: User
  gui_title_agent_1: Plato
  human_role: user

  experience_logs:
    save: True
    load: False
    path: logs/CamRest_GUI_speech

  global_arguments:
    ontology: example/domains/CamRestaurants-rules.json
    database: example/domains/CamRestaurants-dbase.db
    db_type: sql
    domain: CamRest

DIALOGUE:
  num_dialogues: 1
  initiative: user
  domain: CamRest


AGENT_0:
  role: system
  modules: 3
  stateful_module: 1

  MODULE_0:
    package: plato.agent.component.nlu.slot_filling_nlu
    class: SlotFillingNLU

  MODULE_1:
    package: plato.agent.component.dialogue_manager.dialogue_manager_generic
    class: DialogueManagerGeneric
    arguments:
      DST:
        package: plato.agent.component.dialogue_state_tracker.slot_filling_dst
        class: SlotFillingDST

      policy:
        package: plato.agent.component.dialogue_policy.slot_filling_policy
        class: HandcraftedPolicy

  MODULE_2:
    package: plato.agent.component.nlg.slot_filling_nlg
    class: SlotFillingNLG

#  MODULE_3:
#    package: plato.agent.component.agent.GenericHelpers
#    class: GenericSpeechSynthesiserHelper
